version: "3.6"

services:
    php:
        build:
            context: ./php
        image: ${CURRENT_PHP_IMG}
        ports:
            - 9000:9000
        volumes:
            - ${HOST_ROOT}:${CONTAINER_ROOT}
        working_dir: ${CONTAINER_ROOT}
        tty: true
        networks:
            - bx-net
